name: Flutter CI (iOS unsigned + Android)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ios:
    name: iOS (unsigned) build
    runs-on: macos-14    # Xcode 15.x; use macos-15 for Xcode 16
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'   # gives Dart 3.9.x
          channel: 'stable'
          architecture: arm64         # GitHub macOS-14 runners are Apple Silicon
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Tests
        run: flutter test

      # Build an iOS app WITHOUT code signing (good for CI sanity checks)
      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      # Zip the built .app so you can download it from Actions
      - name: Zip Runner.app
        run: |
          cd build/ios/iphoneos
          zip -r Runner.app.zip Runner.app

      - name: Upload iOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-Runner-app
          path: build/ios/iphoneos/Runner.app.zip

  android:
    name: Android build (AAB)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 'stable'
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Tests
        run: flutter test

      - name: Build Android App Bundle
        run: flutter build appbundle --release

      - name: Upload Android artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: build/app/outputs/bundle/release/*.aab

